Support for gRPC client configuration
aseovic/helidon pull request #102
Opened 2019-05-02 04:20 UTC by makannan

Support for gRPC client configuration

2019-05-02 10:00 UTC, thegridman requested changes

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +            throw new IllegalArgumentException("No channel configuration named " + name + " exists in the config file.");
Helidon config can come from various sources so saying `exists in the config file` is not actually correct. You should probably just say `"No channel named '" + name + "' has been configured"`

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +    Map<String, ChannelConfig> getChannelConfigs() {
Change this method name to `channels()`. The Helidon coding standards say not to use `get` and `set` prefixes for getter and setter methods. Also from comments we had on the initial PR they do not seem to like the use of the word `Config` for things that are not actually Helidon config related. So I would just call the method `channels`.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +    public Channel getChannel(String name)
Change this method name to `channel`. The Helidon coding standards say not to use get and set prefixes for getter and setter methods.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +        this.channelConfigs = new HashMap<>();
What is wrong with replacing all of this with `this.channelConfigs = new HashMap<>(channelConfigs);`. I see why a copy constructor is required for `ChannelConfig` and actually why you cannot just copy the `Map` that is passed in.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +public class GrpcClientConfiguration {
I'm thinking that we should possibly change this class name. Maybe just call it `GrpcChannels` or something as all it actually is is a provider of pre-configured `Channel` instances.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> + * GrpcClientConfiguration holds configuration details that can be used to create and
All this class really is is a factory for pre-configured gRPC `Channel` instances. I'm not sure about having a whole paragraph about configuration when using configuration is entirely optional and an instance of this class could have been built without using any configuration at all.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> + * Once bootstrapped, an instance of {@link io.helidon.grpc.client.GrpcClientConfiguration} can
You are not really "querying" an instance of `io.helidon.grpc.client.GrpcClientConfiguration`, it is a factory that builds named `Channels`. An instance of a `Channel` is built using the previously configured settings for that `Channel`.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +    public static class SslConfig {
This class is pretty much identical to `SslConfiguration` in the `server` module. It would have been better to just move the `SslConfiguration` class from the gRPC `server` module into the gRPC `core` module and then use that class instead of this. You can add the config annotations to the `SslConfiguration` class.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +    public static class ChannelConfig {
I would move this class out of here and make it a proper separate class, probably called `GrpcChannel` as the Helidon guys do not like the use of the name Config in anything that is not specifically Helidon config (which is why we had to change class names before).

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +        private ChannelConfig(ChannelConfig other) {
As previously commented on, this class is immutable so why is there a need for a copy constructor.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +            @Value(withDefault = "localhost")
You should use `@Value(withDefault = DEFAULT_HOST)` so that the default is only set in one place, i.e. in the constant.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +            @Value(withDefault = "1408")
You should use `@Value(withDefault = DEFAULT_PORT)` so that the default is only set in one place, i.e. in the constant.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +        public Builder add(String name, ChannelConfig chCfg) {
I'd change this method name to either `addChannel` or just `channel`.
We need to support in-process channels. These will only have a name and no host or port or SSL config.  We'd need another method that is `inProcessChannel(String name)` or addInProcessChannel(String name)`.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +            channelConfigs.put(name, chCfg);
You probably want to check that both of these values are non-null and that `name` is also not blank and throw NPE or `IllegalArgumentException` if they are and add this rule to the JavaDoc.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +package io.helidon.grpc.client;
General comments for the whole file.

1. JavaDocs - comments for `@param`, `@returns` `@throws` etc should all start with lowercase letter and not end with a full stop. The only comments that use full stops are in the main body of the JavaDoc comment.

2. As Helidon code standards state, getter and setter methods should not use `get` and `set` prefixes.

3. All Builder classes should implement the correctly genericised Helidon `io.helidon.common.Builder` interface.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +        if (cfg.sslConfig == null || !cfg.sslConfig.isEnabled()) {
Directly accessing fields of another class may fail the SpotBugs checks. All access to fields is supposed to via getter methods (which would have to be the case here based on my comment below about extracting `ChannelConfig` into a stand-alone class).

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +        public Builder add(String name, ChannelConfig chCfg) {
I'm not a big fan of cryptic variable names like `chCfg`, what is wrong with just `config`.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +     * ChannelConfig contains the details to configure a {@link io.grpc.Channel}.
ChannelConfig contains the configuration for a {@link io.grpc.Channel}.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +         * @return The SslConfig instance (or null if no configuration was specified).
@return The {@link SslConfig} instance (or {@code null} if no SSL configuration was specified)

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +    public static GrpcClientConfiguration create() {
The comment for this method is wrong, it will not have any defaults. The way the code works a `GrpcClientConfiguration` instance will be created with an empty `channelConfigs` map so _all_ calls to `getChannel` will then throw `IllegalArgumentException`. Which kind of makes this method a bit pointless as it will create a `GrpcClientConfiguration` that always throws an exception.

We _could_ leave the method here if we change the builder so that if when `build` is called there are no channels configured we create a default channel with some default name say `default` or `localhost` and default its host and port to `localhost:1408`. The there is the option to use this method where we _know_ we only want the default. Outside of testing though I'm not sure where we'd use the default of `localhost:1408`, and even most testing would use some ephemeral port.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/pom.xml
> +   <dependency>
Why do you need to add HOCON as a test dependency, what config in your tests is in anything but YAML?

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/test/java/io/helidon/grpc/client/GrpcClientConfigurationIT.java
> +import com.oracle.bedrock.runtime.LocalPlatform;
You do not need to use Bedrock for ports. If you start the server and set the port to zero (i.e. `GrpcServerConfiguration.builder().name(name).port(0)` and the server will start on an ephemeral port. You can then call `server.port()` after it has started to find out the port it has bound to.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/test/java/io/helidon/grpc/client/GrpcClientConfigurationIT.java
> +        assertThrows(io.grpc.StatusRuntimeException.class, () -> invokeUnary(port1WaySSL, WITH_NO_SSL));
You need to assert that the right status is in the exception. Off the top of my head I don't know what the is but you might get a `StatusRuntimeException` for some other reason in which case the test should fail.
For example
```
StatusRuntimeException ex = assertThrows(StatusRuntimeException.class, () -> invokeUnary(port1WaySSL, WITH_NO_SSL));
assertThat(ex.getStatus().getCode(), is(Status.PERMISSION_DENIED));
```
Obviously change `Status.PERMISSION_DENIED` to the actual correct status.

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/test/java/io/helidon/grpc/client/GrpcClientConfigurationIT.java
> +        assertThrows(io.grpc.StatusRuntimeException.class, () -> invokeUnary(port2WaySSL, WITH_NO_SSL));
Same as the above comment about asserting exceptions

2019-05-02 10:00 UTC, thegridman commented on grpc/client/src/test/java/io/helidon/grpc/client/GrpcClientConfigurationIT.java
> +        assertThrows(io.grpc.StatusRuntimeException.class, () -> invokeUnary(port2WaySSL, WITH_CA_CERT + WITH_CLIENT_CERT));
Same as the above comment about asserting exceptions

2019-05-02 16:23 UTC, makannan commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +            throw new IllegalArgumentException("No channel configuration named " + name + " exists in the config file.");
Done.

2019-05-02 16:24 UTC, makannan commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +    Map<String, ChannelConfig> getChannelConfigs() {
Done.

2019-05-02 16:26 UTC, makannan commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +    public Channel getChannel(String name)
Done.

2019-05-02 16:28 UTC, makannan commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +        this.channelConfigs = new HashMap<>();
I presume what I have is fine. Not changing anything here.

2019-05-02 16:31 UTC, makannan commented on grpc/client/pom.xml
> +   <dependency>
Well, I initially had a HOCON config file and switched to yaml. 
I will remove that dependency.

2019-05-02 16:34 UTC, makannan commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +public class GrpcClientConfiguration {
How about `GrpcChannelsProvider` or `ConfiguredGrpcChannelProvider` ?
Not changing now until I hear from you.

2019-05-02 16:44 UTC, makannan commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> + * GrpcClientConfiguration holds configuration details that can be used to create and
Updated javadoc to have just this:
/**
 * GrpcClientConfiguration is a factory for pre-configured gRPC Channel instances.
 */

2019-05-02 16:45 UTC, makannan commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> + * Once bootstrapped, an instance of {@link io.helidon.grpc.client.GrpcClientConfiguration} can
```
/**
 * GrpcClientConfiguration is a factory for pre-configured gRPC Channel instances.
 */
```

2019-05-02 17:51 UTC, makannan commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +    public static class SslConfig {
The SSLConfiguration class will be used by both client and server right? In which case it should have `clientCert` `clientKey` `serverCert` etc. Also, does jdkSSL apply only for server ?

In other words, do we really want to move that class to core ?

2019-05-02 18:58 UTC, makannan commented on grpc/client/src/main/java/io/helidon/grpc/client/GrpcClientConfiguration.java
> +        this.channelConfigs = new HashMap<>();
Changed as suggested. Done.

2019-05-03 15:47 UTC, thegridman approved these changes

2019-05-03 15:47 UTC, merged